# Generated by Django 6.0 on 2025-12-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='我的公司', max_length=100)),
                ('lock_date', models.DateField(blank=True, help_text='關帳日', null=True)),
                ('enable_budget_workflow', models.BooleanField(default=False, help_text='啟用預決算簽核流程')),
                ('default_approval_config', models.JSONField(blank=True, default=dict, help_text='預設簽核流程設定')),
                ('allowed_domains', models.JSONField(default=list, help_text='允許訪問的網域名稱')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
            },
        ),
    ]
